
trigger:
- master

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'

stages:
# - stage: build
#   jobs:
#   - job: front
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '10.x'
#       displayName: 'Install Node.js'

#     - script: |
#         cd ./front
#         npm install
#         npm run build
#       displayName: 'npm install and build'

#     - script: |
#         cd ./front
#         npx nuxt generate
#       displayName: 'generate prod code'

#   - job: backend
#     pool:
#       vmImage: 'ubuntu-latest'
    
#     steps:

#     - script: |
#         cd ./backend
#         go build
#       displayName: 'go build'
    
#     - script: |
#         cd ./backend
#         make test
#       displayName: 'go test'

- stage: deploy
  jobs:
  - job: app_engine_deploy
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:

    - script: |
        cd ./backend

        echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
        docker pull google/cloud-sdk:252.0.0-alpine
        docker run -ti -v /tmp:/tmp --name gcloud-config google/cloud-sdk:252.0.0-alpine gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
        docker run -ti -v $(pwd):/tmp/recout/backend --volumes-from gcloud-config google/cloud-sdk:252.0.0-alpine gcloud version

        make ciinit
        npm install --prefix ../front/
        echo "----make generate----"
        npm run generate --prefix ../front/
        # make generate
        ls -l ../front/
        ls -l ../front/dist/
        echo "---make pack----"
        make pack

        docker run -ti -v $(pwd):/tmp/recout/backend --volumes-from gcloud-config google/cloud-sdk:252.0.0-alpine cd /tmp/recout/backend && gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy

        # clean
        docker rm -f gcloud-config
        rm /tmp/$CI_PIPELINE_ID.json

      displayName: 'deploy'
