
trigger:
- master

jobs:
- job: front
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      cd ./front
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      cd ./front
      npx nuxt generate
    displayName: 'generate prod code'

- job: backend
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:

  - script: |
      cd ./backend
      go build
    displayName: 'go build'
  
  - script: |
      cd ./backend
      make test
    displayName: 'go test'
