
trigger:
- master

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'

stages:
# - stage: build
#   jobs:
#   - job: front
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '10.x'
#       displayName: 'Install Node.js'

#     - script: |
#         cd ./front
#         npm install
#         npm run build
#       displayName: 'npm install and build'

#     - script: |
#         cd ./front
#         npx nuxt generate
#       displayName: 'generate prod code'

#   - job: backend
#     pool:
#       vmImage: 'ubuntu-latest'
    
#     steps:

#     - script: |
#         cd ./backend
#         go build
#       displayName: 'go build'
    
#     - script: |
#         cd ./backend
#         make test
#       displayName: 'go test'

- stage: deploy
  jobs:
  - job: app_engine_deploy
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        # front
        cd ./front
        echo $FIREBASE_CONFIG > ./firebase.config.ts
        npm install
        NODE_ENV=production RECOUT_URL='/v1' npx nuxt generate
        ls -l ./dist/

        # backend
        cd ../backend
        make ciinit
        make pack

        echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/credential.json
        docker pull google/cloud-sdk:252.0.0-alpine
        docker run -v /tmp:/tmp --name gcloud-config google/cloud-sdk:252.0.0-alpine gcloud auth activate-service-account --key-file /tmp/credential.json
        docker run -v $(pwd):/tmp/recout/backend --volumes-from gcloud-config google/cloud-sdk:252.0.0-alpine gcloud version

        docker run -v $(pwd):/tmp/recout/backend --volumes-from gcloud-config google/cloud-sdk:252.0.0-alpine cd /tmp/recout/backend && gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy

        # clean
        docker rm -f gcloud-config
        rm /tmp/credential.json
      env:
        FIREBASE_CONFIG: $(FIREBASE_CONFIG)
        DEPLOY_KEY_FILE_PRODUCTION: $(DEPLOY_KEY_FILE_PRODUCTION)
        PROJECT_ID_PRODUCTION: $(PROJECT_ID_PRODUCTION)

      displayName: 'deploy'
