runtime: go111
includes:
  - secret.yml
env_variables:
  RO_ENV: prod
handlers:
- url: /recout
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: '*'
    Access-Control-Allow-Methods: "GET,POST,OPTIONS"