// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/gmidorii/recout/backend/app"
	datastore2 "github.com/gmidorii/recout/backend/infra/datastore"
	"github.com/gmidorii/recout/backend/infra/pixela"
	"go.mercari.io/datastore"
)

// Injectors from wire.go:

func InitRecoutApp(gClient datastore.Client, ctn app.Container, env string) (app.Recout, error) {
	recout, err := datastore2.NewRecoutClient(gClient, env)
	if err != nil {
		return nil, err
	}
	user, err := datastore2.NewUserClient(gClient, env)
	if err != nil {
		return nil, err
	}
	continues := datastore2.NewContinuesClient(gClient, env)
	client := pixela.NewClient()
	appRecout := app.NewRecout(ctn, recout, user, continues, client)
	return appRecout, nil
}

func InitUserApp(gClient datastore.Client, ctn app.Container, env string) (app.User, error) {
	user, err := datastore2.NewUserClient(gClient, env)
	if err != nil {
		return nil, err
	}
	appUser := app.NewUser(ctn, user)
	return appUser, nil
}
